on: [push]
jobs:
  Main:
    name: JMeter CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: Bundle-Engine-Test/Bundle-Engine-XO-Test.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
