on: [push]
jobs:
  Main:
    name: JMeter CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir reports
      
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: Bundle-Engine-Test/Bundle-Engine-XO-Test.jmx
          args: "-e -o ./reports/html/"
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error
          
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error
